#!/bin/bash

###############################################################################
#
# This scirpt takes ARM format ECMWF monthly files, and concatenates them
# into a single timeseries for the length required.
#
# Two files are produced - one for upper air variables, one for surface variables
#
# The base time must be consistent with the other input files to the
# variational analysis. Currently base time is set as the begining of the first month
# of data specified by 'months'.
#
##############################################################################
# Options

# Set the begin and end time ###########
date=$(which gdate 2> /dev/null)
src=$(basename $0)
if [ -z "$date" ];then
    date=$(which date)
fi
if [ -z "$date" ];then
    echo "${src} : Can't find date or gdate, if you are on osx considere installing coreutils"
    exit 1
fi

#           yyyymmdd hhmm
# Set the times we require
date_begin=$(echo ${3}|sed s"/_/ /g")
date_end=$(echo ${4}|sed s"/_/ /g")
declare -a months=${@:5}
# these are the months we need #########


# Input directories ####################

ipt_dir_upa=${1%/}
ipt_dir_surf=${1%/}
opt_dir=${2%/}

if [ ! -z $opt_dir ];then
    mkdir -p ${opt_dir}
fi

# OUTPUT FILES #########################

fileout_upa="${2%/}/upa_p.nc"
fileout_surf="${2%/}/surf_p.nc"

##############################################################################

in_dir_upa=${ipt_dir_upa}
in_dir_surf=${ipt_dir_surf}

# Get file names #############################################################
 
for mon in ${months[*]}
do
 # Find the files required
   filein_upa[$i]=$(find ${in_dir_upa%/}/*upa*${mon}*)
   filein_surf[$i]=$(find ${in_dir_surf%/}/*surf*${mon}*)

   i=$(($i+1))
done
# Set baseline dates and time cutoffs ########################################


base_date=$(echo $months|awk '{print $1}')
base_time=$($date -u -d "${base_date}" +%s )


t_begin=$(($($date -u -d "${date_begin}" +%s ) - $($date -u -d "${base_date}" +%s )))
t_end=$(($($date -u -d "${date_end}" +%s ) - $($date -u -d "${base_date}" +%s )))

t_begin=$(echo $t_begin|awk '{printf("%.2f",$1/86400.0)}')
t_end=$(echo $t_end|awk '{printf("%.2f",$1/86400.0)}')

base_date=$($date -u -d $(($base_date)) +%Y-%m-%d )
delta=$(echo $t_end $t_begin |awk {'printf("%.2f",$1-$2)'})

# Print some stuff to screen ###############################################s
echo " ************************************"
echo " "
echo "       Creating 3D_put file"
echo " "
echo " ************************************"
echo " "
echo "${src} : Time-series defined:"
echo "${src} : from $($date -d "$date_begin" +"%d. %b %Y %H:%M") to $($date -d "$date_end" +"%d. %b %Y %H:%M") (${delta} days) after $base_date"
echo " "
# Do the concatenation, and clean up a few things #############################
ncrcat -h -O -o ${fileout_upa} ${filein_upa[*]}
ncap -h -O -s "time = time_offset^1/86400.0" ${fileout_upa} ${fileout_upa}
ncatted -h -a units,time,a,c,"days since ${base_date}" ${fileout_upa}
ncatted -h -a units,time,a,c,"days since ${base_date} 00:00:00 UTC" ${fileout_upa}
ncks -h -O -d time,${t_begin},${t_end} ${fileout_upa} ${fileout_upa}

ncrcat -h -O -o ${fileout_surf} ${filein_surf[*]}
ncap -h -O -s "time = time_offset^1/86400.0" ${fileout_surf} ${fileout_surf}
ncatted -h -a units,time,a,c,"days since ${base_date} 00:00:00 UTC" ${fileout_surf}
ncks -h -O -d time,${t_begin},${t_end} ${fileout_surf} ${fileout_surf}
