.TH "/home/unimelb.edu.au/mbergemann/va_analysis/src/numerics.f90" 3 "Mon Apr 16 2018" "Variational Analysis" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/unimelb.edu.au/mbergemann/va_analysis/src/numerics.f90 \- 
.SH SYNOPSIS
.br
.PP
.SS "Modules"

.in +1c
.ti -1c
.RI "module \fBnumerics\fP"
.br
.in -1c
.SS "Functions/Subroutines"

.in +1c
.ti -1c
.RI "subroutine \fBnumerics::itps\fP (KS, KB, D, DS)"
.br
.ti -1c
.RI "subroutine \fBnumerics::gmean\fP (MG, DP, NV, NST, NT, TSMOOTH)"
.br
.ti -1c
.RI "subroutine \fBnumerics::smooth\fP (ARRAY, N, FILTER_WIDTH, CYCLIC)"
.br
.ti -1c
.RI "subroutine \fBnumerics::caldev\fP (DU, KT, KS, NSTU, NTU, NP, NVU, DEVM2)"
.br
.ti -1c
.RI "subroutine \fBnumerics::horizontal_field\fP (NST, LON, LAT, X, Y, F, DZDX, DZDY, DIVU, DIVV)"
.br
.ti -1c
.RI "subroutine \fBnumerics::line_fit_xyz\fP (N, X, Y, Z, DZDX, DZDY, Z0)"
.br
.ti -1c
.RI "subroutine \fBnumerics::windown\fP (N, X, DX, X1, L0, L1)"
.br
.ti -1c
.RI "subroutine \fBnumerics::assim\fP (NP, DP, P, KS, KB, KT, NSTU, LONU, LATU, DU, NSTS, LONS, LATS, DSS, DIVBVAR, FCX, FCY, FPX, FPY, BUDGET, NADVAR, WVAR, DUS)"
.br
.ti -1c
.RI "subroutine \fBnumerics::calc_budget_layer\fP (NP, NTU, P, BUDGET_LAYER, BUDGET_COLUMNS, AVE_QS, AVE_SS)"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Variational Analysis from the source code\&.
