#!/bin/bash
#
###################################################################################
#
# This script reads surface variables from the ECMWF analysis data 
# in a format as from the ARM data archive
# (netcdf with the ARM time convention)
#
# The input files are named: 
#
# twpecmwfdarsuppX1.c1.yyyymm01.000000.cdf
# twpecmwfdarsurfX1.c1.yyyymm01.000000.cdf
#
# Currently each file has one month of data in it. 
# The twp region is a 7x7 grid at 0.5 deg resolution
#
# 
#
# It outputs a single netcdf file for the time period specified using the dates variable
# It averages the data in space over the gridpoints specified in the masking file 
# This is a crude average for an irregularly shaped domain, but given the uncertainties
# in the analysis itself this should be ok.
#
# Currently the temporal resolution of the data is not changed by this program
#
#
#
echoerr() {
  echo "$@" 1>&2
  exit 257
}


#
##################################################################################
#
# Options
src=$(basename $0)
date=$(which gdate 2> /dev/null)
if [ -z "$date" ];then
    date=$(which date)
fi
if [ -z "$date" ];then
    echoerr "$src : Can't find date or gdate, if you are on osx considere installing coreutils"
fi

# Set where relevant files are located
ipt_dir=${1%/}/
opt_dir=${2%/}/
mkdir -p $opt_dir
# Set the output filename
outfile=${3%/}
seas=${4}
wrkdir=$(dirname $(readlink -f $0))

# Set the times we require
date_begin=$(echo ${5}|sed s"/_/ /g")
date_end=$(echo ${6}|sed s"/_/ /g")
declare -a months=${@:6}
# Names of all the months in between our two dates
##################################################################################


# Set the full paths to the input and output directories
outfile=${opt_dir}${outfile}


var1="time,time_offset,base_time,sktsfc,spsfc,no10usfc,no10vsfc,no2tsfc,no2dsfc,lccsfc,mccsfc,hccsfc,zsfc,twcsfc,srsfc"
var2="ewsssfc,nssssfc,sshfsfc,slhfsfc,ssrsfc,strsfc,tsrsfc,ttrsfc,tccsfc,ssrdsfc,strdsfc"

# Set baseline dates and time cutoffs ########################################

base_date=$(echo ${date_begin}|awk '{print $1}')
base_time=$($date -u -d "${base_date} 0000" +%s )

time_begin=$(($($date -u -d "${date_begin}" +%s ) - $($date -u -d "${base_date} 0000" +%s )))
time_end=$(($($date -u -d "${date_end}" +%s ) - $($date -u -d "${base_date} 0000" +%s )))

time_begin=$(echo $time_begin|awk '{printf("%.2f",$1/86400.0)}')
time_end=$(echo $time_end|awk '{printf("%.2f",$1/86400.0)}')

delta=$(echo $time_end $time_begin |awk {'printf("%.2f",$1-$2)'})

base_date=$($date -u -d $(($base_date)) +%Y-%m-%d )

# Print some stuff to screen ###############################################s
echo " ************************************"
echo " "
echo "       Creating 2D_put file"
echo " "
echo " ************************************"
echo " "
echo "${src} : Time-series defined:"
echo "${src} : from $(date -u -d "$date_begin" +"%d. %b %Y %H:%M") to $(date -u -d "$date_end" +"%d. %b %Y %H:%M") (${delta} days) after $base_date"
echo " "


let i=0
nday=$(echo $date_begin|awk '{print $1}') #Get the first day
let nday=$($date -u -d "${nday} 0000" +%s) # Make it 00:00, in case it is not
end=$(echo $date_end|awk '{print $1}') #Get the last date
let end=$($date -u -d "${end} 1800" +%s) # Make it 00:00, in case it is not
# concatenate files (nco knows about arm conventions in time_offset and base_time, but not in time itself
declare -a file_surf=$(find ${ipt_dir}*surf*????????*.cdf 2> /dev/null)
declare -a file_supp=$(find ${ipt_dir}*supp*????????*.cdf 2> /dev/null)
#Check for monthly or daily files
nn=$(echo $date_begin | awk '{print $1}')
nn=$(echo ${nn:0:6})
let ii=0
for dd in {2..31};do
  dn=$(echo $dd|awk '{printf("%02d",$1)}')
  ff[$ii]=$(find ${ipt_dir%/}/*ecmwf*.${nn}${dn}.*.cdf 2> /dev/null)
done
if [ -z "${f[*]}" ];then
  monthly=true
else
  monthly=false
fi
# Get file names #############################################################
if $monthly ;then
  tstring=$($date -u -d @${nday} +'%Y%m01')
  let nday=$($date -u -d "${tstring} 0000" +%s) # Make it 00:00, in case it is not
  while [ ${nday} -lt ${end} ];do
    tstring=$($date -u -d @${nday} +'%Y%m01')

    file_supp[$i]=$(find ${ipt_dir%/}/*supp*${tstring}*.cdf 2> /dev/null)
    file_surf[$i]=$(find ${ipt_dir%/}/*surf*${tstring}*.cdf 2> /dev/null)
    let YYYY=$(echo ${tstring:0:4})
    let MM=$(echo ${tstring:4:2})
    i=$(($i+1))
    let delta=$(cal $MM $YYYY| awk 'NF {DAYS = $NF}; END {print DAYS}'|awk '{print $1*86400}')
    let nday=$((${nday}+${delta})) #Increase by one day (86400 sec)
  done
else
  while [ ${nday} -lt ${end} ] ;do
    tstring=$(date -u -d @${nday} +'%Y%m%d')
   # Find the files required
     file_supp[$i]=$(find ${ipt_dir%/}/*supp*${tstring}*.cdf 2> /dev/null)
     file_surf[$i]=$(find ${ipt_dir%/}/*surf*${tstring}*.cdf 2> /dev/null)

     nday=$(($nday+86400)) #Increase by one day (86400 sec)
     i=$(($i+1))
   done
fi
ncrcat -h -O -o ${opt_dir%/}/tmp_surf.cdf ${file_surf[*]}
ncrcat -D 0 -h -O -o ${opt_dir%/}/tmp_supp.cdf ${file_supp[*]}
ncks -D 0 -h -O -v "${var1}" ${opt_dir%/}/tmp_surf.cdf $outfile
ncks -D 0 -h -A -v "${var2}" ${opt_dir%/}/tmp_supp.cdf $outfile

# fix the 'time' variable
ncap -h -O -s "time = time_offset^1/86400.0" ${outfile} ${outfile}
ncatted -h -a units,time,a,c,"days since ${base_date} 00:00:00 UTC" ${outfile}

# make a masking file for the domain we require
${wrkdir%}/make_mask_ecmwf -i "${outfile}" -o ${opt_dir%}/mask_${seas}.nc -d square


# average over the gridpoints specified by the masking file.
# this is just a sum over the points inside the domain... nothing fancy.
ncks -D 0 -h -A -v masking_var ${opt_dir%/}/mask_${seas}.nc "${outfile}"
ncwa -D 0 -h -O -a latitude,longitude -m masking_var -T gt -M -1.0 "${outfile}" "${outfile}"

# clean up and make like Tim's file ###########################

# remove unwanted var
ncks -D 0 -h -O -x -v latitude,masking_var,base_time,longitude "${outfile}" "${outfile}"

# fix up baseline
tmp=$(echo ${date_begin}|awk '{print $1'})
ncap -h -A -s "bdate=${tmp}" "${outfile}" "${outfile}"
ncatted -h -a units,bdate,o,c,"yyyymmdd" "${outfile}"
ncatted -h -a long_name,bdate,o,c,"baseline date" "${outfile}"


# change from units * sec to the right ones

deltat=$(ncks -D 0 -v time -d time,1,1,1 $outfile)
# At some stage I understood sed and wrote this. 
deltat=$(echo ${deltat}]} | sed 's/.*\(time[1]\)*\([0-9]\.[0-9]*[0-9]\).*/\2/')

deltat=$deltat
deltat_sec=$(echo $deltat|awk '{printf("%.2f",$1*86400)}')

echo "${src} : Temporal resolution: $deltat_sec seconds"
#var1="time,time_offset,base_time,sktsfc,spsfc,no10usfc,no10vsfc,no2tsfc,no2dsfc,lccsfc,mccsfc,hccsfc,zsfc,twcsfc,srsfc"
#var2="ewsssfc,nssssfc,sshfsfc,slhfsfc,ssrsfc,strsfc,tsrsfc,ttrsfc,tccsfc,ssrdsfc,strdsfc"


script1="ewsssfc=ewsssfc/$deltat_sec"
script2="nssssfc=nssssfc/$deltat_sec"

script3="sshfsfc=sshfsfc/$deltat_sec"
script4="slhfsfc=slhfsfc/$deltat_sec"
script5="ssrsfc=ssrsfc/$deltat_sec"
script6="strsfc=strsfc/$deltat_sec" 
script7="tsrsfc=tsrsfc/$deltat_sec" 
script8="ttrsfc=ttrsfc/$deltat_sec"

script9="ssrdsfc=ssrdsfc/$deltat_sec" 
script10="strdsfc=strdsfc/$deltat_sec"

script11="spsfc=spsfc/100"

#ncap -h -O -s $script1 $outfile $outfile
#ncap -h -O -s $script2 $outfile $outfile
ncap -h -O -s $script3 $outfile $outfile
ncap -h -O -s $script4 $outfile $outfile
ncap -h -O -s $script5 $outfile $outfile
ncap -h -O -s $script6 $outfile $outfile
ncap -h -O -s $script7 $outfile $outfile
ncap -h -O -s $script8 $outfile $outfile
ncap -h -O -s $script9 $outfile $outfile
ncap -h -O -s $script10 $outfile $outfile
ncap -h -O -s $script11 $outfile $outfile


ncap -O -h -s "surf_net=ssrsfc+strsfc" "${outfile}" "${outfile}"
# Fix attributes

ncatted -h -a units,ssrsfc,o,c,"W/m2" "${outfile}"
ncatted -h -a long_name,ssrsfc,o,c,"SW net surface radiation" "${outfile}"

ncatted -h -a units,strsfc,o,c,"W/m2" "${outfile}"
ncatted -h -a long_name,strsfc,o,c,"LW net surface radiation" "${outfile}"

ncatted -h -a units,surf_net,o,c,"W/m2" "${outfile}"
ncatted -h -a long_name,surf_net,o,c,"total net surface radiation" "${outfile}"

ncatted -h -a units,ttrsfc,o,c,"W/m2" "${outfile}"
ncatted -h -a long_name,ttrsfc,o,c,"TOA long-wave radiation" "${outfile}"

ncatted -h -a units,tsrsfc,o,c,"W/m2" "${outfile}"
ncatted -h -a long_name,tsrsfc,o,c,"TOA short-wave radiation" "${outfile}"

ncatted -h -a units,ssrdsfc,o,c,"W/m2" "${outfile}"
ncatted -h -a long_name,ssrdsfc,o,c,"Surface solar radiation down" "${outfile}"

ncatted -h -a units,strdsfc,o,c,"W/m2" "${outfile}"
ncatted -h -a long_name,strdsfc,o,c,"Surface long-wave radiation down" "${outfile}"

ncatted -h -a units,ewsssfc,o,c,"Ns/m2" "${outfile}"
ncatted -h -a long_name,ewsssfc,o,c,"E-W surface stress" "${outfile}"

ncatted -h -a units,nssssfc,o,c,"Ns/m2" "${outfile}"
ncatted -h -a long_name,nssssfc,o,c,"N-S surface stress" "${outfile}"

ncatted -h -a units,sshfsfc,o,c,"W/m2" "${outfile}"
ncatted -h -a long_name,sshfsfc,o,c,"surface sensible heat-flux" "${outfile}"

ncatted -h -a units,slhfsfc,o,c,"W/m2" "${outfile}"
ncatted -h -a long_name,slhfsfc,o,c,"surface latent heat-flux" "${outfile}"

ncatted -h -a units,spsfc,o,c,"hPa" "${outfile}"

# ok. Now need to move the flux data by three hours. This is nasty.
# make two files of the desired time period. One 6 hours ahead of the other
# some time variables

tfl1=$(echo ${time_begin} ${deltat} |awk '{printf("%.2f",$1+$2)}')
tfl2=$(echo ${time_end} ${deltat}|awk '{printf("%.2f",$1+$2)}')
ncks -D 0 -h -O -d "time,$tfl1,$tfl2" ${outfile} "${outfile%.nc}_tmp.nc"


tfl1=$(echo ${time_begin} | awk '{printf("%.2f",$1)}')
tfl2=$(echo ${time_end} | awk '{printf("%.2f",$1)}')
ncks -D 0 -h -O -d "time,$tfl1,$tfl2" ${outfile} ${outfile}

# line the two time regions up
ncap -D 0 -h -O -s "time = time - ${deltat}" "${outfile%.nc}_tmp.nc" "${outfile%.nc}_tmp.nc"

# average the fluxes between t and t+dt
var3="ewsssfc,nssssfc,sshfsfc,slhfsfc,ssrsfc,strsfc,tsrsfc,ttrsfc,ssrdsfc,strdsfc,surf_net"
ncflint -h -O -v $var3 ${outfile} "${outfile%.nc}_tmp.nc" "${outfile%.nc}_tmp.nc"
#exit
# put the averaged fluxes in the original file
ncks -D 0 -h -A "${outfile%.nc}_tmp.nc" ${outfile}


ncks -h -O -d time,${time_begin},${time_end} ${outfile} ${outfile}
# The variational analysis likes the names to be like this:
ncrename -D 0 -h -O -v tsrsfc,swt -v ttrsfc,lwt ${outfile}



# remove temporary files
rm -f "${outfile%.nc}_tmp.nc"
rm -f ${opt_dir%/}/*.cdf
rm -f ${opt_dir%/}/*.tmp
rm -f ${opt_dir%/}/mask.nc


