.TH "cli" 3 "Tue Apr 17 2018" "Variational Analysis" \" -*- nroff -*-
.ad l
.nh
.SH NAME
cli \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <radar_error\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "char * \fBinfile\fP"
.br
.ti -1c
.RI "char * \fBerrorstats_file\fP"
.br
.ti -1c
.RI "char * \fBoutfile\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 18 of file radar_error\&.h\&.
.SH "Field Documentation"
.PP 
.SS "char* cli::errorstats_file"

.PP
Definition at line 20 of file radar_error\&.h\&.
.SS "char* cli::infile"

.PP
Definition at line 19 of file radar_error\&.h\&.
.SS "char* cli::outfile"

.PP
Definition at line 21 of file radar_error\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Variational Analysis from the source code\&.
