.TH "/home/unimelb.edu.au/mbergemann/va_analysis/src/constants.f90" 3 "Tue Apr 17 2018" "Variational Analysis" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/unimelb.edu.au/mbergemann/va_analysis/src/constants.f90 \- 
.SH SYNOPSIS
.br
.PP
.SS "Modules"

.in +1c
.ti -1c
.RI "module \fBconstants\fP"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "real(kind=rk8), parameter \fBconstants::pi\fP = 3\&.14159265"
.br
.ti -1c
.RI "real(kind=rk8), parameter \fBconstants::rearth\fP = 6371000"
.br
.ti -1c
.RI "real(kind=rk8), parameter \fBconstants::omega\fP = 7\&.292E\-05"
.br
.ti -1c
.RI "real(kind=rk8), parameter \fBconstants::rd\fP = 287\&.04"
.br
.ti -1c
.RI "real(kind=rk8), parameter \fBconstants::rw\fP = 461\&.50"
.br
.ti -1c
.RI "real(kind=rk8), parameter \fBconstants::g\fP = 9\&.8"
.br
.ti -1c
.RI "real(kind=rk8), parameter \fBconstants::lv0\fP = 2\&.5E6"
.br
.ti -1c
.RI "real(kind=rk8), parameter \fBconstants::lv\fP = 2\&.501E6"
.br
.ti -1c
.RI "real(kind=rk8), parameter \fBconstants::ls\fP = 2\&.834E6"
.br
.ti -1c
.RI "real(kind=rk8), parameter \fBconstants::ls1\fP = 2\&.834E6"
.br
.ti -1c
.RI "real(kind=rk8), parameter \fBconstants::cpd\fP = 1005\&.7"
.br
.ti -1c
.RI "real(kind=rk8), parameter \fBconstants::cpv\fP = 1870\&.0"
.br
.ti -1c
.RI "real(kind=rk8), parameter \fBconstants::cl\fP = 4190\&.0"
.br
.ti -1c
.RI "real(kind=rk8), parameter \fBconstants::t0\fP = 273\&.15"
.br
.ti -1c
.RI "real(kind=rk8), parameter \fBconstants::cd\fP = 3\&.0E\-3"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Variational Analysis from the source code\&.
