.TH "errorstats" 3 "Fri Apr 27 2018" "Variational Analysis" \" -*- nroff -*-
.ad l
.nh
.SH NAME
errorstats \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <radar_error\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "size_t \fBnstns\fP"
.br
.ti -1c
.RI "double * \fBlon\fP"
.br
.ti -1c
.RI "double * \fBlat\fP"
.br
.ti -1c
.RI "double * \fBmu\fP"
.br
.ti -1c
.RI "double * \fBsigma\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 34 of file radar_error\&.h\&.
.SH "Field Documentation"
.PP 
.SS "double* errorstats::lat"

.PP
Definition at line 37 of file radar_error\&.h\&.
.SS "double* errorstats::lon"

.PP
Definition at line 36 of file radar_error\&.h\&.
.SS "double* errorstats::mu"

.PP
Definition at line 38 of file radar_error\&.h\&.
.SS "size_t errorstats::nstns"

.PP
Definition at line 35 of file radar_error\&.h\&.
.SS "double* errorstats::sigma"

.PP
Definition at line 39 of file radar_error\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Variational Analysis from the source code\&.
