.TH "/home/unimelb.edu.au/mbergemann/va_analysis/src/lu.f90" 3 "Tue Apr 17 2018" "Variational Analysis" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/unimelb.edu.au/mbergemann/va_analysis/src/lu.f90 \- 
.SH SYNOPSIS
.br
.PP
.SS "Modules"

.in +1c
.ti -1c
.RI "module \fBlu\fP"
.br
.in -1c
.SS "Functions/Subroutines"

.in +1c
.ti -1c
.RI "subroutine \fBlu::ludcmp\fP (A, N, INDX, D, CODE)"
.br
.ti -1c
.RI "subroutine \fBlu::lubksb\fP (A, N, INDX, B)"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Variational Analysis from the source code\&.
