.TH "/home/unimelb.edu.au/mbergemann/va_analysis/src/physics.f90" 3 "Fri Apr 27 2018" "Variational Analysis" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/unimelb.edu.au/mbergemann/va_analysis/src/physics.f90 \- 
.SH SYNOPSIS
.br
.PP
.SS "Modules"

.in +1c
.ti -1c
.RI "module \fBphysics\fP"
.br
.in -1c
.SS "Functions/Subroutines"

.in +1c
.ti -1c
.RI "subroutine \fBphysics::s_r_to_t_z\fP (P, PS, ZS, S, R, T, Z)"
.br
.ti -1c
.RI "subroutine \fBphysics::t_r_to_s_z\fP (P, PS, ZS, T, R, S, Z)"
.br
.ti -1c
.RI "subroutine \fBphysics::diverg\fP (UNITH, VAR, U, V, DIVU, DIVV, DIV1)"
.br
.ti -1c
.RI "subroutine \fBphysics::fcorlx\fP (UNITH, NSTU, F, V, FCX1)"
.br
.ti -1c
.RI "subroutine \fBphysics::fcorly\fP (UNITH, NSTU, F, U, FCY1)"
.br
.ti -1c
.RI "subroutine \fBphysics::fpgd\fP (UNITH, Z, DZDX, FP1)"
.br
.ti -1c
.RI "subroutine \fBphysics::height\fP (NP, KS, KT, P, T, R, Z)"
.br
.ti -1c
.RI "subroutine \fBphysics::calht2\fP (PS, ZS, N, P, TC, R, HT, DEW)"
.br
.ti -1c
.RI "subroutine \fBphysics::calc_state2\fP (P, T, TD, E, Z, R, RH, H, HDRY, S)"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Variational Analysis from the source code\&.
