.TH "portable" 3 "Mon Apr 16 2018" "Variational Analysis" \" -*- nroff -*-
.ad l
.nh
.SH NAME
portable \- 
.SH SYNOPSIS
.br
.PP
.SS "Variables"

.in +1c
.ti -1c
.RI "integer, parameter \fBik1\fP = SELECTED_INT_KIND(2)"
.br
.ti -1c
.RI "integer, parameter \fBik2\fP = SELECTED_INT_KIND(4)"
.br
.ti -1c
.RI "integer, parameter \fBik4\fP = SELECTED_INT_KIND(9)"
.br
.ti -1c
.RI "integer, parameter \fBrk4\fP = SELECTED_REAL_KIND(4, 30)"
.br
.ti -1c
.RI "integer, parameter \fBrk8\fP = SELECTED_REAL_KIND(10, 200)"
.br
.in -1c
.SH "Variable Documentation"
.PP 
.SS "integer, parameter portable::ik1 = SELECTED_INT_KIND(2)"

.PP
Definition at line 11 of file portable\&.f90\&.
.PP
.nf
11 INTEGER, PARAMETER  :: ik1 = selected_int_kind(2)       ! Probably a 1 or 2 byte integer\&.
.fi
.SS "integer, parameter portable::ik2 = SELECTED_INT_KIND(4)"

.PP
Definition at line 12 of file portable\&.f90\&.
.PP
.nf
12 INTEGER, PARAMETER  :: ik2 = selected_int_kind(4)       ! Probably a 2 byte integer\&.
.fi
.SS "integer, parameter portable::ik4 = SELECTED_INT_KIND(9)"

.PP
Definition at line 13 of file portable\&.f90\&.
.PP
.nf
13 INTEGER, PARAMETER  :: ik4 = selected_int_kind(9)       ! Probably a 4 byte integer\&.
.fi
.SS "integer, parameter portable::rk4 = SELECTED_REAL_KIND(4, 30)"

.PP
Definition at line 15 of file portable\&.f90\&.
.PP
.nf
15 INTEGER, PARAMETER  :: rk4 = selected_real_kind(4,30)   ! Probably a 4 byte real\&.
.fi
.SS "integer, parameter portable::rk8 = SELECTED_REAL_KIND(10, 200)"

.PP
Definition at line 17 of file portable\&.f90\&.
.PP
.nf
17 INTEGER, PARAMETER  :: rk8 = selected_real_kind(10,200) ! Probably a 8 byte real\&.
.fi
.SH "Author"
.PP 
Generated automatically by Doxygen for Variational Analysis from the source code\&.
