.TH "/home/unimelb.edu.au/mbergemann/va_analysis/src/portable.f90" 3 "Fri Apr 27 2018" "Variational Analysis" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/unimelb.edu.au/mbergemann/va_analysis/src/portable.f90 \- 
.SH SYNOPSIS
.br
.PP
.SS "Modules"

.in +1c
.ti -1c
.RI "module \fBportable\fP"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "integer, parameter \fBportable::ik1\fP = SELECTED_INT_KIND(2)"
.br
.ti -1c
.RI "integer, parameter \fBportable::ik2\fP = SELECTED_INT_KIND(4)"
.br
.ti -1c
.RI "integer, parameter \fBportable::ik4\fP = SELECTED_INT_KIND(9)"
.br
.ti -1c
.RI "integer, parameter \fBportable::rk4\fP = SELECTED_REAL_KIND(4, 30)"
.br
.ti -1c
.RI "integer, parameter \fBportable::rk8\fP = SELECTED_REAL_KIND(10, 200)"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Variational Analysis from the source code\&.
