.TH "radar" 3 "Fri Apr 27 2018" "Variational Analysis" \" -*- nroff -*-
.ad l
.nh
.SH NAME
radar \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <radar_error\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "size_t \fBnx\fP"
.br
.ti -1c
.RI "size_t \fBny\fP"
.br
.ti -1c
.RI "double * \fBrain_rate\fP"
.br
.ti -1c
.RI "double * \fBlon\fP"
.br
.ti -1c
.RI "double * \fBlat\fP"
.br
.ti -1c
.RI "int * \fBnearest_stn\fP"
.br
.ti -1c
.RI "double ** \fBrain_rate_pdf\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 24 of file radar_error\&.h\&.
.SH "Field Documentation"
.PP 
.SS "double* radar::lat"

.PP
Definition at line 29 of file radar_error\&.h\&.
.SS "double* radar::lon"

.PP
Definition at line 28 of file radar_error\&.h\&.
.SS "int* radar::nearest_stn"

.PP
Definition at line 30 of file radar_error\&.h\&.
.SS "size_t radar::nx"

.PP
Definition at line 25 of file radar_error\&.h\&.
.SS "size_t radar::ny"

.PP
Definition at line 26 of file radar_error\&.h\&.
.SS "double* radar::rain_rate"

.PP
Definition at line 27 of file radar_error\&.h\&.
.SS "double** radar::rain_rate_pdf"

.PP
Definition at line 31 of file radar_error\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Variational Analysis from the source code\&.
