.TH "/home/unimelb.edu.au/mbergemann/va_analysis/src/settings.f90" 3 "Tue Apr 17 2018" "Variational Analysis" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/unimelb.edu.au/mbergemann/va_analysis/src/settings.f90 \- 
.SH SYNOPSIS
.br
.PP
.SS "Modules"

.in +1c
.ti -1c
.RI "module \fBsettings\fP"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "real(kind=rk8), parameter \fBsettings::pstart\fP =200\&.0"
.br
.ti -1c
.RI "real(kind=rk8), parameter \fBsettings::pcrit\fP =200\&.0"
.br
.ti -1c
.RI "integer(kind=ik4), parameter \fBsettings::nvbudget_column\fP =5"
.br
.ti -1c
.RI "integer(kind=ik4), parameter \fBsettings::nvbudget_layer\fP =6"
.br
.ti -1c
.RI "integer(kind=ik4), parameter \fBsettings::ntermmax\fP =7"
.br
.ti -1c
.RI "integer(kind=ik4), parameter \fBsettings::ntermmaxv\fP =8"
.br
.ti -1c
.RI "integer(kind=ik4), parameter \fBsettings::nad\fP =3"
.br
.ti -1c
.RI "integer(kind=ik4), parameter \fBsettings::nstx0\fP =10"
.br
.ti -1c
.RI "integer(kind=ik4), parameter \fBsettings::nsty0\fP =9"
.br
.ti -1c
.RI "integer(kind=ik4), parameter \fBsettings::nvu\fP =10"
.br
.ti -1c
.RI "integer(kind=ik4), parameter \fBsettings::nvs\fP = NVU"
.br
.ti -1c
.RI "real(kind=rk8), parameter \fBsettings::pt\fP =90\&.0"
.br
.ti -1c
.RI "integer(kind=ik4), parameter \fBsettings::start_year\fP =2004"
.br
.ti -1c
.RI "integer(kind=ik4), parameter \fBsettings::start_month\fP =10"
.br
.ti -1c
.RI "integer(kind=ik4), parameter \fBsettings::start_day\fP = 1"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Variational Analysis from the source code\&.
