.TH "setup" 3 "Tue Apr 17 2018" "Variational Analysis" \" -*- nroff -*-
.ad l
.nh
.SH NAME
setup \- 
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "def \fBfile_search\fP (file)"
.br
.ti -1c
.RI "def \fBcheckenv\fP (var, alt)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "\fBOs\fP = platform\&.system()"
.br
.ti -1c
.RI "\fBhost\fP = socket\&.gethostname()\&.lower()"
.br
.ti -1c
.RI "float \fBsleep\fP = 0\&.2"
.br
.ti -1c
.RI "string \fBPath\fP = '/opt/local'"
.br
.ti -1c
.RI "bool \fBhelp\fP = True"
.br
.ti -1c
.RI "string \fBtxt\fP"
.br
.ti -1c
.RI "\fBaltnames\fP = dict(sed='sed',awk='awk',date='date')"
.br
.ti -1c
.RI "\fBLDFLAGS\fP = LDFLAGS\&.split(',')"
.br
.ti -1c
.RI "list \fBmissing_package\fP = []"
.br
.ti -1c
.RI "tuple \fBcheckbin\fP"
.br
.ti -1c
.RI "\fBstatus\fP = False"
.br
.ti -1c
.RI "\fBfn\fP"
.br
.ti -1c
.RI "list \fBmissing_module\fP = []"
.br
.ti -1c
.RI "\fBmethod\fP = dict(pbs='qsub',slurm='sbatch')[\fBBATCH\fP]"
.br
.ti -1c
.RI "\fBBATCH\fP = BATCH\&.lower()"
.br
.ti -1c
.RI "\fBproj_file\fP = os\&.path\&.join(os\&.pardir,'\&.proj')"
.br
.ti -1c
.RI "\fBa\fP = raw_input('Warning option for creating batch jobs is set but no PROJECT if given, is that correct? [Y|n]: ')"
.br
.ti -1c
.RI "\fBf\fP = open(\fBproj_file\fP,'w')"
.br
.ti -1c
.RI "\fBMAIL\fP = raw_input('No user email is given, enter now: ')"
.br
.ti -1c
.RI "string \fBbatch_header\fP = u''"
.br
.ti -1c
.RI "string \fBbatch_job\fP"
.br
.ti -1c
.RI "\fBbash_script\fP = os\&.path\&.join(os\&.pardir,'submit_%s\&.sh'%\fBBATCH\fP)"
.br
.ti -1c
.RI "list \fBversion_conflict\fP = []"
.br
.ti -1c
.RI "\fBcmd\fP = \fBaltnames\fP[command]"
.br
.ti -1c
.RI "\fBprocess\fP = Popen([\fBcmd\fP,'\-\-version'],stdout=PIPE)"
.br
.ti -1c
.RI "\fBoutput\fP"
.br
.ti -1c
.RI "\fBerr\fP"
.br
.ti -1c
.RI "\fBexit_code\fP = process\&.wait()"
.br
.ti -1c
.RI "\fBfl\fP = float(b'\&.'\&.join(re\&.findall(b'\\d+',output\&.split(b'\\n')[0])[0:2]))"
.br
.ti -1c
.RI "string \fBmakefile_var\fP"
.br
.ti -1c
.RI "string \fBmakefile_radar\fP"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "def setup\&.checkenv ( var,  alt)"

.PP
Definition at line 26 of file setup\&.py\&.
.PP
.nf
26 def checkenv(var,alt):
27     try:
28         return os\&.environ[var]
29     except KeyError:
30         return alt
31 
32 #netcdfmod=os\&.popen('locate netcdf\&.mod 2> /dev/null')\&.read()\&.strip()
33 
34 FC=checkenv('FC','gfortran')
35 CC=checkenv('CC','gcc')
36 FFLAGS=checkenv('FFLAGS','-ffixed-line-length-0 -std=legacy -g -O3 -fimplicit-none -fsign-zero -fbounds-check -Wpedantic -fno-automatic')
37 CFLAGS=checkenv('CFLAGS','-O3 -Wpedantic')
38 INCLUDE=checkenv('INCLUDE',os\&.path\&.join(Path,'include'))\&.replace(':',',')
39 LDFLAGS=checkenv('LD_LIBRARY_PATH',os\&.path\&.join(Path,'lib'))\&.replace(':',',')
40 FLIBS=checkenv('FLIBS','netcdff')
41 CLIBS=checkenv('CLIBS','netcdf,m')
42 BATCH=checkenv('BATCH',0)
43 PROJECT=checkenv('PROJECT',None)
44 MAIL=checkenv('EMAIL','')
45 PREFIX=os\&.path\&.dirname(os\&.path\&.dirname(os\&.path\&.abspath(__file__)))
46 #if len(netcdfmod):
47 #    INCLUDE+=',%s'%os\&.path\&.dirname(netcdfmod)
48 try:
49     ar=sys\&.argv[1:]
50     help=False
51     for b in ar:
52         a=b\&.replace('--','')\&.upper()
53         if b\&.startswith('-h') or b\&.startswith('--h'):
54             help=True
55         if b\&.lower()\&.startswith('--prefix'):
56             PREFIX = a\&.lower()\&.split('=')[1]
57         if a\&.startswith('FC'):
58             FC=a\&.split('=')[-1]
59         if a\&.startswith('FFLAGS'):
60             FCFLAGS=a\&.split('=')[-1]\&.replace(',',' ')
61         if a\&.startswith('CFLAGS'):
62             CFLAGS=a\&.split('=')[-1]\&.replace(',',' ')
63         if a\&.startswith('INCLUDE'):
64             INCLUDE=a\&.split('=')[-1]
65         if a\&.startswith('LD_LIBRARY_PATH'):
66             LDFLAGS=a\&.split('=')[-1]
67         if a\&.startswith('CLIBS'):
68             CLIBS=a\&.split('=')[-1]
69         if a\&.startswith('FLIBS'):
70             FLIBS=a\&.split('=')[-1]
71         if a\&.startswith('BATCH'):
72             batch=a\&.split('=')[-1]\&.lower()
73             try :
74               BATCH={'p':'pbs','s':'slurm','ll':'ll'}[batch[0]]
75             except KeyError:
76               sys\&.stderr\&.write('Batch option should be one of the following: pbs, slurm\n')
77               sys\&.exit(257)
78         if a\&.startswith('PROJECT'):
79           PROJECT=a\&.split('=')[-1]
80         if a\&.startswith('EMAIL'):
81           MAIL=a\&.split('=')[-1]
82 
.fi
.SS "def setup\&.file_search ( file)"

.PP
Definition at line 18 of file setup\&.py\&.
.PP
.nf
18 def file_search(file):
19     time\&.sleep(sleep)
20     for path in os\&.environ['PATH']\&.split(':'):
21         fn=os\&.path\&.join(path,file)
22         if os\&.path\&.isfile(os\&.path\&.join(path,fn)):
23             return True,fn
24     return False,None
25 
.fi
.SH "Variable Documentation"
.PP 
.SS "setup\&.a = raw_input('Warning option for creating batch jobs is set but no PROJECT if given, is that correct? [Y|n]: ')"

.PP
Definition at line 201 of file setup\&.py\&.
.SS "setup\&.altnames = dict(sed='sed',awk='awk',date='date')"

.PP
Definition at line 142 of file setup\&.py\&.
.SS "setup\&.bash_script = os\&.path\&.join(os\&.pardir,'submit_%s\&.sh'%\fBBATCH\fP)"

.PP
Definition at line 319 of file setup\&.py\&.
.SS "setup\&.BATCH = BATCH\&.lower()"

.PP
Definition at line 198 of file setup\&.py\&.
.SS "string setup\&.batch_header = u''"

.PP
Definition at line 212 of file setup\&.py\&.
.SS "setup\&.batch_job"

.PP
Definition at line 240 of file setup\&.py\&.
.SS "tuple setup\&.checkbin"
\fBInitial value:\fP
.PP
.nf
1 = (\
2         ('gnu make','make',1),
3         ('fortran compiler',FC,1),
4         ('nc-config','nc-config',1),
5         ('ncap','ncap',1),
6         ('ncatted','ncatted',1),
7         ('ncbo','ncbo',1),
8         ('ncdiff','ncdiff',1),
9         ('ncdump','ncdump',1),
10         ('ncea','ncea',1),
11         ('ncecat','ncecat',1),
12         ('nces','nces',1),
13         ('ncgen','ncgen',1),
14         ('ncks','ncks',1),
15         ('ncrcat','ncrcat',1),
16         ('ncrename','ncrename',1),
17         ('ncwa','ncwa',1),
18         ('date','date',2),
19         ('awk','awk',2),
20         ('sed','sed',2),
21         ('gdl or idl','gdl',2)
22         )
.fi
.PP
Definition at line 149 of file setup\&.py\&.
.SS "setup\&.cmd = \fBaltnames\fP[command]"

.PP
Definition at line 350 of file setup\&.py\&.
.SS "setup\&.err"

.PP
Definition at line 358 of file setup\&.py\&.
.SS "setup\&.exit_code = process\&.wait()"

.PP
Definition at line 359 of file setup\&.py\&.
.SS "setup\&.f = open(\fBproj_file\fP,'w')"

.PP
Definition at line 206 of file setup\&.py\&.
.SS "setup\&.fl = float(b'\&.'\&.join(re\&.findall(b'\\d+',output\&.split(b'\\n')[0])[0:2]))"

.PP
Definition at line 360 of file setup\&.py\&.
.SS "setup\&.fn"

.PP
Definition at line 175 of file setup\&.py\&.
.SS "bool setup\&.help = True"

.PP
Definition at line 85 of file setup\&.py\&.
.SS "string setup\&.host = socket\&.gethostname()\&.lower()"

.PP
Definition at line 4 of file setup\&.py\&.
.SS "setup\&.LDFLAGS = LDFLAGS\&.split(',')"

.PP
Definition at line 144 of file setup\&.py\&.
.SS "setup\&.MAIL = raw_input('No user email is given, enter now: ')"

.PP
Definition at line 210 of file setup\&.py\&.
.SS "string setup\&.makefile_radar"

.PP
Definition at line 466 of file setup\&.py\&.
.SS "string setup\&.makefile_var"

.PP
Definition at line 391 of file setup\&.py\&.
.SS "setup\&.method = dict(pbs='qsub',slurm='sbatch')[\fBBATCH\fP]"

.PP
Definition at line 197 of file setup\&.py\&.
.SS "list setup\&.missing_module = []"

.PP
Definition at line 195 of file setup\&.py\&.
.SS "list setup\&.missing_package = []"

.PP
Definition at line 147 of file setup\&.py\&.
.SS "string setup\&.Os = platform\&.system()"

.PP
Definition at line 3 of file setup\&.py\&.
.SS "setup\&.output"

.PP
Definition at line 358 of file setup\&.py\&.
.SS "string setup\&.Path = '/opt/local'"

.PP
Definition at line 13 of file setup\&.py\&.
.SS "setup\&.process = Popen([\fBcmd\fP,'\-\-version'],stdout=PIPE)"

.PP
Definition at line 357 of file setup\&.py\&.
.SS "setup\&.proj_file = os\&.path\&.join(os\&.pardir,'\&.proj')"

.PP
Definition at line 199 of file setup\&.py\&.
.SS "float setup\&.sleep = 0\&.2"

.PP
Definition at line 10 of file setup\&.py\&.
.SS "bool setup\&.status = False"

.PP
Definition at line 175 of file setup\&.py\&.
.SS "string setup\&.txt"

.PP
Definition at line 86 of file setup\&.py\&.
.SS "list setup\&.version_conflict = []"

.PP
Definition at line 347 of file setup\&.py\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Variational Analysis from the source code\&.
