.TH "/home/unimelb.edu.au/mbergemann/va_analysis/src/time.f90" 3 "Tue Apr 17 2018" "Variational Analysis" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/unimelb.edu.au/mbergemann/va_analysis/src/time.f90 \- 
.SH SYNOPSIS
.br
.PP
.SS "Modules"

.in +1c
.ti -1c
.RI "module \fBtime\fP"
.br
.in -1c
.SS "Functions/Subroutines"

.in +1c
.ti -1c
.RI "subroutine \fBtime::days_to_date\fP (STYEAR, STMONTH, STDAY, DAYS, YYYY, MO, DD, HH, MM, SS)"
.br
.ti -1c
.RI "integer(kind=ik4) function \fBtime::date_time_to_unix\fP (YYYY, MO, DD, HH, MM, SS)"
.br
.ti -1c
.RI "logical function \fBtime::leapyear\fP (YEAR)"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Variational Analysis from the source code\&.
