.TH "/home/unimelb.edu.au/mbergemann/va_analysis/src/variational_analysis.f90" 3 "Fri Apr 27 2018" "Variational Analysis" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/unimelb.edu.au/mbergemann/va_analysis/src/variational_analysis.f90 \- 
.SH SYNOPSIS
.br
.PP
.SS "Functions/Subroutines"

.in +1c
.ti -1c
.RI "program \fBvariational_analysis\fP"
.br
.in -1c
.SH "Function/Subroutine Documentation"
.PP 
.SS "program variational_analysis ()"

.PP
Definition at line 18 of file variational_analysis\&.f90\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Variational Analysis from the source code\&.
